# FOSUserBundle Configuration
fos_user:
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        email:
            from_email:
                address:        noreply@disciple-builder.com
                sender_name:    No Reply | Disciple Builder
    registration:
        confirmation:
            enabled: true
            from_email:
                address: noreply@disciple-builder.com
                sender_name: No Reply | Disciple Builder
    db_driver: orm
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: info@disciple-builder.com
        sender_name: info@disciple-builder.com