swiftmailer:
    #url: '%env(MAILER_URL)%'
    host: mail.disciple-builder.com
    transport: smtp
    username: info@disciple-builder.com
    password: disciplebuilder317
    port: 587
    sender_address: info@disciple-builder.com
    encryption: tls
    auth_mode: login
    spool: { type: 'memory' }
    stream-options:
        ssl:
            allow_self_signed : true
            verify_peer: false
