vich_uploader:
    db_driver: orm
    twig: true
    mappings:
        application_resume:
            uri_prefix: /uploads/resumes
            upload_destination: '%kernel.project_dir%/public/uploads/resumes'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true